app = "n8n-app"  # Nome do seu app Fly.io
primary_region = "gru"

[env]
  N8N_HOST = "imgn8nsrv1.fly.dev"
  WEBHOOK_URL = "https://imgn8nsrv1.fly.dev/"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "admin"
  GENERIC_TIMEZONE = "America/Sao_Paulo"
  N8N_COOKIE_SECURE = "true"
  QUEUE_MODE = "redis"
  REDIS_HOST = "seu-redis.fly.dev"
  REDIS_PORT = "6379"
  N8N_RUNNERS_ENABLED = "true"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = "false"
  DB_TYPE = "postgresdb"
  DB_POSTGRESDB_HOST = "seu-postgres.internal"
  DB_POSTGRESDB_PORT = "5432"
  DB_POSTGRESDB_DATABASE = "n8n"
  DB_POSTGRESDB_USER = "n8n_user"
  DB_POSTGRESDB_PASSWORD = "n8n_pass"

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[services]
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
